name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      id-token: write
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run tests with 1 second slow down 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          record: true
          group: 'Slow down 1 second'
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run tests without slow down 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # we have already installed everything
          install: false
          record: true
          group: 'Disabled slow down'
          env: commandDelay=false
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
